/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import com.google.gson.Gson;
import com.google.gson.JsonStreamParser;
import netscape.javascript.JSObject;

import java.io.*;
import java.net.HttpURLConnection;
import java.net.MalformedURLException;
import java.net.URL;

public class App {
    public static void main(String[] args) {


      //System.out.println(getLocalQuote());
      getAPIQuote();

    }

    public static String getLocalQuote() {

      Gson gson = new Gson();

      Quote[] quote = null;

      try {
        File file = new File("assets/recentquotes.json");
        FileReader reader = new FileReader(file);
        quote = gson.fromJson(reader, Quote[].class);
      } catch (FileNotFoundException e) {
        System.out.println("file not found " + e);
      }

      int quoteNum = (int) (Math.random() * quote.length);

      String returnQuote = "Author: " + quote[quoteNum].author + "\n" + "Quote: " + quote[quoteNum].text;

      return returnQuote;

    }

    public static void getAPIQuote() {

        Gson gson = new Gson();

        URL url = null;

        APIQuote quoteFromAPI = null;

        try {
            url = new URL("https://favqs.com/api/qotd");
        } catch (MalformedURLException e) {
            System.out.println("bad url");
            return;
        }
        try {
            HttpURLConnection connection = (HttpURLConnection) url.openConnection();
            BufferedReader in = new BufferedReader(
                    new InputStreamReader(connection.getInputStream()));
            String currentline = in.readLine();
            while (currentline != null) {
                //System.out.println(currentline);
                quoteFromAPI = gson.fromJson(currentline, APIQuote.class);
                System.out.println(quoteFromAPI);
                currentline = in.readLine();
            }
            //System.out.println("woooot.  :)");
        } catch (IOException e) {
            System.out.println("the internet did not work.");
            e.printStackTrace();
        }
    }

}
